services:
  # This is the service for your PHP application
  app:
    build: .
    container_name: my_php_app
    ports:
      - "8000:80"
    volumes:
          - ./:/var/www/html
    depends_on:
      - mariadb
    restart: unless-stopped

  # This is the service for your database
  mariadb:
    image: mariadb:11.4
    container_name: mariadb_db
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: laragon_db
      MARIADB_USER: laragon
      MARIADB_PASSWORD: laragon
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: unless-stopped

  # This is the service for your database manager
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - mariadb
    restart: unless-stopped

volumes:
  mariadb_data: